"""
MC Hub AI — Audio Preprocessor (v2)
=====================================
Reads metadata_master.txt (generated by download_dataset.py) and:
  1. Validates each WAV file (duration, sample rate, quality checks)
  2. Resamples to 22050Hz (optimal for GPT-SoVITS TTS training)
  3. Normalizes audio volume (peak normalization)
  4. Filters out samples that are too short (<1s) or too long (>15s)
  5. Exports clean dataset into training_data/wavs/ with updated metadata
  6. Generates separate STT metadata (for Whisper fine-tuning)

Usage:
  python preprocess_audio.py
"""

import os
import sys
import shutil
import numpy as np
import soundfile as sf
import librosa
from pathlib import Path
from tqdm import tqdm

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

# ----------------------------------------------------------------
#  Config
# ----------------------------------------------------------------
MASTER_METADATA   = Path("./training_data/metadata_master.txt")
OUTPUT_DIR        = Path("./training_data")
TTS_WAVS_DIR      = OUTPUT_DIR / "tts_wavs"    # For GPT-SoVITS
STT_WAVS_DIR      = OUTPUT_DIR / "stt_wavs"    # For Whisper fine-tune
TTS_METADATA_OUT  = OUTPUT_DIR / "tts_metadata.txt"
STT_METADATA_OUT  = OUTPUT_DIR / "stt_metadata.txt"

TTS_SAMPLE_RATE   = 22050   # GPT-SoVITS requires 22050Hz
STT_SAMPLE_RATE   = 16000   # Whisper requires 16000Hz
MIN_DURATION_SEC  = 1.0     # Skip segments shorter than 1s
MAX_DURATION_SEC  = 15.0    # Skip segments longer than 15s (too noisy)


# ----------------------------------------------------------------
#  Helper: Peak normalize audio to -3dBFS
# ----------------------------------------------------------------
def peak_normalize(audio: np.ndarray, target_db: float = -3.0) -> np.ndarray:
    peak = np.max(np.abs(audio))
    if peak < 1e-6:
        return audio
    target_amplitude = 10 ** (target_db / 20.0)
    return audio * (target_amplitude / peak)


# ----------------------------------------------------------------
#  Main preprocessor
# ----------------------------------------------------------------
def preprocess():
    TTS_WAVS_DIR.mkdir(parents=True, exist_ok=True)
    STT_WAVS_DIR.mkdir(parents=True, exist_ok=True)

    if not MASTER_METADATA.exists():
        print(f"[ERROR] {MASTER_METADATA} not found!")
        print("  -> Run download_dataset.py first")
        return

    # Read all metadata entries
    raw_lines = MASTER_METADATA.read_text(encoding="utf-8").strip().splitlines()
    valid_lines = [l for l in raw_lines if l.strip() and "|" in l]
    print(f"[PREPROCESS] Found {len(valid_lines)} entries in metadata_master.txt")

    tts_metadata = []
    stt_metadata = []
    skipped_missing = 0
    skipped_short   = 0
    skipped_long    = 0
    errors          = 0

    for idx, line in enumerate(tqdm(valid_lines, desc="Processing")):
        parts = line.strip().split("|")
        if len(parts) < 4:
            continue

        rel_path, speaker, lang, text = parts[0], parts[1], parts[2], "|".join(parts[3:])
        text = text.strip()

        # Resolve path (relative to project root)
        wav_path = Path(".") / rel_path
        if not wav_path.exists():
            skipped_missing += 1
            continue

        try:
            # Load and validate
            audio_raw, sr_raw = librosa.load(str(wav_path), sr=None, mono=True)
            duration = len(audio_raw) / sr_raw

            if duration < MIN_DURATION_SEC:
                skipped_short += 1
                continue
            if duration > MAX_DURATION_SEC:
                skipped_long += 1
                continue

            # --- TTS Branch: 22050Hz, normalized ---
            audio_tts = librosa.resample(audio_raw, orig_sr=sr_raw, target_sr=TTS_SAMPLE_RATE)
            audio_tts = peak_normalize(audio_tts, target_db=-3.0)

            tts_filename = f"tts_{idx:06d}.wav"
            tts_path = TTS_WAVS_DIR / tts_filename
            sf.write(str(tts_path), audio_tts, TTS_SAMPLE_RATE, subtype="PCM_16")
            tts_metadata.append(f"training_data/tts_wavs/{tts_filename}|{speaker}|{lang}|{text}")

            # --- STT Branch: 16000Hz ---
            audio_stt = librosa.resample(audio_raw, orig_sr=sr_raw, target_sr=STT_SAMPLE_RATE)

            stt_filename = f"stt_{idx:06d}.wav"
            stt_path = STT_WAVS_DIR / stt_filename
            sf.write(str(stt_path), audio_stt, STT_SAMPLE_RATE, subtype="PCM_16")
            stt_metadata.append(f"training_data/stt_wavs/{stt_filename}|{text}")

        except Exception as e:
            errors += 1
            continue

    # Write output metadata
    TTS_METADATA_OUT.write_text("\n".join(tts_metadata), encoding="utf-8")
    STT_METADATA_OUT.write_text("\n".join(stt_metadata), encoding="utf-8")

    # Summary
    print("\n" + "="*60)
    print(" PREPROCESS COMPLETE")
    print("="*60)
    print(f"  Input entries    : {len(valid_lines)}")
    print(f"  TTS samples out  : {len(tts_metadata)}  -> {TTS_WAVS_DIR}")
    print(f"  STT samples out  : {len(stt_metadata)}  -> {STT_WAVS_DIR}")
    print(f"  Skipped missing  : {skipped_missing}")
    print(f"  Skipped too short: {skipped_short}")
    print(f"  Skipped too long : {skipped_long}")
    print(f"  Errors           : {errors}")
    print(f"\n  TTS metadata -> {TTS_METADATA_OUT}")
    print(f"  STT metadata -> {STT_METADATA_OUT}")
    print("\n  Next: Fine-tune GPT-SoVITS with tts_wavs/")


if __name__ == "__main__":
    preprocess()
